### ISSUE TITLE
NPM update

### ISSUE THREAD

**Issue by agilecollab** [rossj/rackit#19]
Hi RossJ, 

We use this package as a dependency in one of our older projects, I see that you fixed rackit File = ../node_modules/pkgcloud a long time ago... 

However these changes haven't been updated in your npm package... so every time we install we manually make the change. 

Any chance you could push these changes to your npm lib? 

Thanks!

**Comment by rossj** [comment]
Oh no! Sorry for the dependency rot. Published as 0.2.3.

**Comment by agilecollab** [comment]
Thanks! Mucho appreciated!
